/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import java.util.*;
import processing.core.*;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    @Order(-1)
    public void simpleTest() {
        App testApp = new App();
        assertNotNull(testApp);
        // PApplet.runSketch(new String[] {"App"}, testApp);
        // testApp.setup();
        // assertTrue(testApp.fps != 0);
        // // assertNotNull(testApp.m);
        // testApp = null;

    }

    
}
